import { Group, Notification, Transaction } from '@/types/savings';

export const mockGroups: Group[] = [
  {
    id: '1',
    name: 'Family Savings Circle',
    description: 'Monthly family savings for emergency fund and investments',
    members: [
      {
        id: '1',
        userId: '1',
        name: 'Amina Wanjiku',
        joinedAt: '2024-01-15',
        totalContributed: 45000,
        isAdmin: true,
        paymentStatus: 'up-to-date',
      },
      {
        id: '2',
        userId: '2',
        name: 'John Kamau',
        joinedAt: '2024-01-15',
        totalContributed: 40000,
        isAdmin: false,
        paymentStatus: 'up-to-date',
      },
      {
        id: '3',
        userId: '3',
        name: 'Grace Njeri',
        joinedAt: '2024-02-01',
        totalContributed: 35000,
        isAdmin: false,
        paymentStatus: 'pending',
      },
    ],
    totalSavings: 125400,
    contributionAmount: 5000,
    contributionFrequency: 'monthly',
    nextContributionDate: '2024-08-28',
    progress: 82,
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Business Partners Fund',
    description: 'Investment fund for business expansion opportunities',
    members: [
      {
        id: '4',
        userId: '1',
        name: 'Amina Wanjiku',
        joinedAt: '2024-03-01',
        totalContributed: 30000,
        isAdmin: false,
        paymentStatus: 'up-to-date',
      },
    ],
    totalSavings: 89200,
    contributionAmount: 3000,
    contributionFrequency: 'weekly',
    nextContributionDate: '2024-09-05',
    progress: 65,
    isActive: true,
    createdAt: '2024-03-01',
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    userId: '1',
    groupId: '1',
    type: 'contribution',
    amount: 5000,
    description: 'Monthly contribution - Family Savings Circle',
    date: '2024-08-28',
    status: 'completed',
    paymentMethod: 'M-Pesa',
    reference: 'MP240828001',
  },
  {
    id: '2',
    userId: '1',
    groupId: '2',
    type: 'payout',
    amount: 15000,
    description: 'Quarterly payout - Business Partners Fund',
    date: '2024-08-25',
    status: 'completed',
    paymentMethod: 'Bank Transfer',
    reference: 'BT240825002',
  },
  {
    id: '3',
    userId: '1',
    groupId: '1',
    type: 'contribution',
    amount: 3000,
    description: 'Emergency contribution - Family Savings Circle',
    date: '2024-08-22',
    status: 'pending',
    paymentMethod: 'M-Pesa',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'Payment Due Tomorrow',
    message: 'Your monthly contribution of KES 5,000 is due tomorrow for Family Savings Circle',
    type: 'payment_due',
    isRead: false,
    createdAt: '2024-08-27T10:00:00Z',
    actionUrl: '/payments',
  },
  {
    id: '2',
    userId: '1',
    title: 'Payment Received',
    message: 'John Kamau has made a contribution of KES 5,000 to Family Savings Circle',
    type: 'payment_received',
    isRead: false,
    createdAt: '2024-08-26T14:30:00Z',
  },
  {
    id: '3',
    userId: '1',
    title: 'Group Update',
    message: 'Family Savings Circle has reached 82% of the current cycle goal',
    type: 'group_update',
    isRead: true,
    createdAt: '2024-08-25T09:15:00Z',
  },
];